# Generated by Django 3.0.2 on 2020-05-24 13:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('positive', models.BooleanField()),
            ],
            options={
                'db_table': 'booker_categories',
            },
        ),
        migrations.CreateModel(
            name='FinanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booker_sheets',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deleted', models.BooleanField(default=False)),
                ('expected_date', models.DateField()),
                ('expected_percent', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheet')),
            ],
            options={
                'db_table': 'booker_wishlist',
            },
        ),
        migrations.CreateModel(
            name='TemplatedRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceCategory')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheet')),
            ],
            options={
                'db_table': 'booker_templated_rows',
            },
        ),
        migrations.CreateModel(
            name='FinanceSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='booker.FinanceSheet')),
            ],
            options={
                'db_table': 'booker_entry',
            },
        ),
        migrations.AddField(
            model_name='financecategory',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='booker.FinanceSheet'),
        ),
        migrations.CreateModel(
            name='EntryRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('pinned', models.BooleanField(default=False)),
                ('origin_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceCategory')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='booker.FinanceSheetEntry')),
            ],
            options={
                'db_table': 'booker_rows',
                'unique_together': {('name', 'entry', 'category')},
            },
        ),
    ]
