# Generated by Django 3.0.2 on 2020-05-02 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booker_sheets',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deleted', models.BooleanField(default=False)),
                ('expected_date', models.DateField()),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booker_wishlist',
            },
        ),
        migrations.CreateModel(
            name='FinanceSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheet')),
            ],
            options={
                'db_table': 'booker_entry',
            },
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('positive', models.BooleanField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheet')),
            ],
            options={
                'db_table': 'booker_categories',
            },
        ),
        migrations.CreateModel(
            name='FinanceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('pinned', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('origin_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceCategory')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheetEntry')),
            ],
            options={
                'db_table': 'booker_rows',
                'unique_together': {('name', 'entry', 'category')},
            },
        ),
    ]
