# Generated by Django 3.0.2 on 2020-01-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financecategory',
            name='user',
        ),
    ]
