# Generated by Django 3.0.2 on 2020-01-17 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financesheetentry',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheet'),
        ),
        migrations.AddField(
            model_name='financesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financerow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceCategory'),
        ),
        migrations.AddField(
            model_name='financerow',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheetEntry'),
        ),
        migrations.AddField(
            model_name='financecategory',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.FinanceSheet'),
        ),
    ]
